version: '3.8'
services:
    web:
        container_name: python-web
        restart: always
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./.:/app/
        ports:
            - "9870:80"
        networks:
            - sample_app_network
networks:
    sample_app_network:
